// <auto-generated />
namespace Ass2_Shopping_Basket.Migrations.StoreConfiguration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "202101240643037_AddOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
